esphome:
  name: gorenje
  friendly_name: Gorenje

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FAHeRhd9GUaA/+xFBqnWNqCOPnsKfinr38TE+5gydCw="

ota:
  - platform: esphome
    password: "383a93bd31de296a8ef0586d64ce1e35"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gorenje Fallback Hotspot"
    password: "VewlSgVVHAmQ"

captive_portal:
    